export const poseLandmarkNames = [
  "nose",
  "left_eye_inner",
  "left_eye",
  "left_eye_outer",
  "right_eye_inner",
  "right_eye",
  "right_eye_outer",
  "left_ear",
  "right_ear",
  "mouth_left",
  "mouth_right",
  "left_shoulder",
  "right_shoulder",
  "left_elbow",
  "right_elbow",
  "left_wrist",
  "right_wrist",
  "left_pinky",
  "right_pinky",
  "left_index",
  "right_index",
  "left_thumb",
  "right_thumb",
  "left_hip",
  "right_hip",
  "left_knee",
  "right_knee",
  "left_ankle",
  "right_ankle",
  "left_heel",
  "right_heel",
  "left_foot_index",
  "right_foot_index"
] as const;

export const initialLandmarkData = {
  nose: { x: 0, y: 0, z: 0, visibility: 0},
  left_eye_inner: { x: 0, y: 0, z: 0, visibility: 0},
  left_eye: { x: 0, y: 0, z: 0, visibility: 0},
  left_eye_outer: { x: 0, y: 0, z: 0, visibility: 0},
  right_eye_inner: { x: 0, y: 0, z: 0, visibility: 0},
  right_eye: { x: 0, y: 0, z: 0, visibility: 0},
  right_eye_outer: { x: 0, y: 0, z: 0, visibility: 0},
  left_ear: { x: 0, y: 0, z: 0, visibility: 0},
  right_ear: { x: 0, y: 0, z: 0, visibility: 0},
  mouth_left: { x: 0, y: 0, z: 0, visibility: 0},
  mouth_right: { x: 0, y: 0, z: 0, visibility: 0},
  left_shoulder: { x: 0, y: 0, z: 0, visibility: 0},
  right_shoulder: { x: 0, y: 0, z: 0, visibility: 0},
  left_elbow: { x: 0, y: 0, z: 0, visibility: 0},
  right_elbow: { x: 0, y: 0, z: 0, visibility: 0},
  left_wrist: { x: 0, y: 0, z: 0, visibility: 0},
  right_wrist: { x: 0, y: 0, z: 0, visibility: 0},
  left_pinky: { x: 0, y: 0, z: 0, visibility: 0},
  right_pinky: { x: 0, y: 0, z: 0, visibility: 0},
  left_index: { x: 0, y: 0, z: 0, visibility: 0},
  right_index: { x: 0, y: 0, z: 0, visibility: 0},
  left_thumb: { x: 0, y: 0, z: 0, visibility: 0},
  right_thumb: { x: 0, y: 0, z: 0, visibility: 0},
  left_hip: { x: 0, y: 0, z: 0, visibility: 0},
  right_hip: { x: 0, y: 0, z: 0, visibility: 0},
  left_knee: { x: 0, y: 0, z: 0, visibility: 0},
  right_knee: { x: 0, y: 0, z: 0, visibility: 0},
  left_ankle: { x: 0, y: 0, z: 0, visibility: 0},
  right_ankle: { x: 0, y: 0, z: 0, visibility: 0},
  left_heel: { x: 0, y: 0, z: 0, visibility: 0},
  right_heel: { x: 0, y: 0, z: 0, visibility: 0},
  left_foot_index: { x: 0, y: 0, z: 0, visibility: 0},
  right_foot_index: { x: 0, y: 0, z: 0, visibility: 0},
} as const;
